name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Restore NuGet packages
      run: nuget restore WindowsFormApp1.sln
      
    - name: Build Solution
      run: msbuild WindowsFormApp1.sln /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Create Release Directory
      run: |
        mkdir release
        xcopy /E /I /Y "bin\Release\*" "release\"
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 